### 匯入套件

In [300]:
import pandas as pd
import numpy as np
import os


### 匯入檔案

In [301]:
current_dir = os.getcwd()
input_path=os.path.join(current_dir,r"../../data/104_cleaned_0804.csv")

df=pd.read_csv(input_path)
print(df.head())

       上架日期  申請人數        產業              公司名稱  \
0  20250729    10   電腦軟體服務業          不晚科技有限公司
1  20250730    10      光電產業        鉅瀚綠能股份有限公司
2  20250801     3    人力仲介代徵      藝珂人事顧問股份有限公司
3  20250709     9  雜誌／期刊出版業  今周刊_今周文化事業股份有限公司
4  20250730     5   家用電器製造業        金筆企業股份有限公司

                                         description   縣市  \
0  1.熟練數據分析工具，能進行數據清理、分析和建模，分析市場營銷活動的效果，提供報告和改進建議...  台北市
1  1.進行調查數據的彙整，分析調查數據與繪製統計圖表，並撰寫分析建議報告。\n2.依據分析需求...  台中市
2  工作內容：執行全球貿易大數據平台基金業務工作\n1.\t協助數據專案執行、廠商管理、專案委外...  台北市
3  1.【必備】Google Analytics技能。 \n2.【必備】熟稔Excel(函數、樞...  台北市
4  1. 工廠生產數據收集、整理與分析，協助相關人員了解生產狀況\n2. 建立分析指標，追蹤並記...  新北市

                             職稱      工作編號  工作型態         經度  ...       學歷要求  \
0                          數據分析  14325959     0  25.076077  ...     [3, 4]
1                        數據分析專員  14427852     0  24.161955  ...  [4, 5, 6]
2  【外貿協會】數位科技中心-數據分析師｜全球貿易大數據平台  14689540     0  25.033076  ...        [4]
3              數據分析師【今周刊─數位內容部】  14090732     2  25.051911  ...     [4, 5]
4                       數據分析工程師  14720195     2  25.068090  ...        [4]

  是否遠距     薪資上限   薪資下限  工作時段                                職務分類代碼  \
0    0        0      0   NaN  [2007001018, 2016001007, 2004001010]
1    0  9999999  39000   NaN  [2007001018, 2007001022, 2004001010]
2    0        0      0   NaN              [2007001018, 2007001022]
3    0        0      0   NaN              [2007001018, 2007001022]
4    0  9999999  38000   NaN  [2007001022, 2009001003, 2007001009]

                                                條件要求  \
0  {'acceptRole': {'role': [], 'disRole': {'needH...
1  {'acceptRole': {'role': [{'code': 2, 'descript...
2  {'acceptRole': {'role': [], 'disRole': {'needH...
3  {'acceptRole': {'role': [{'code': 64, 'descrip...
4  {'acceptRole': {'role': [], 'disRole': {'needH...

                                                福利制度  員工人數 搜尋關鍵字
0  {'tag': ['年終獎金', '三節獎金/禮品', '不扣薪病假', '結婚禮金', '...   20人  數據分析
1  {'tag': ['年終獎金', '三節獎金/禮品', '零食櫃', '咖啡吧', '帶寵物...   40人  數據分析
2         {'tag': [], 'welfare': '', 'legalTag': []}  暫不提供  數據分析
3  {'tag': [], 'welfare': '★薪資保障\n1.年終獎金 \n2.三節禮金...  217人  數據分析
4  {'tag': ['年終獎金', '三節獎金/禮品', '特殊節日獎金禮品', '咖啡吧',...  108人  數據分析

[5 rows x 22 columns]

# 了解資料

### 查看基本信息(資料類型、缺失值數量、欄位)

In [302]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2501 entries, 0 to 2500
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   上架日期         2501 non-null   int64
 1   申請人數         2501 non-null   int64
 2   產業           2501 non-null   object
 3   公司名稱         2501 non-null   object
 4   description  2501 non-null   object
 5   縣市           2501 non-null   object
 6   職稱           2501 non-null   object
 7   工作編號         2501 non-null   int64
 8   工作型態         2501 non-null   int64
 9   經度           2501 non-null   float64
 10  緯度           2501 non-null   float64
 11  major        2501 non-null   object
 12  學歷要求         2501 non-null   object
 13  是否遠距         2501 non-null   int64
 14  薪資上限         2501 non-null   int64
 15  薪資下限         2501 non-null   int64
 16  工作時段         768 non-null    object
 17  職務分類代碼       2501 non-null   object
 18  條件要求         2501 non-null   object
 19  福利制度         2501 non-null   object
 20  員工人數         2501 non-null   object
 21  搜尋關鍵字        2501 non-null   object
dtypes: float64(2), int64(7), object(13)
memory usage: 430.0+ KB

In [303]:
#了解各欄缺失值數量
df.isnull().sum()

上架日期              0
申請人數              0
產業                0
公司名稱              0
description       0
縣市                0
職稱                0
工作編號              0
工作型態              0
經度                0
緯度                0
major             0
學歷要求              0
是否遠距              0
薪資上限              0
薪資下限              0
工作時段           1733
職務分類代碼            0
條件要求              0
福利制度              0
員工人數              0
搜尋關鍵字             0
dtype: int64

### 進一步移除不需要的欄位資料

In [304]:
df.drop(columns=['工作時段','工作型態','職務分類代碼','薪資上限','福利制度','上架日期','申請人數','搜尋關鍵字'],inplace=True)

In [305]:
df.shape

(2501, 14)

In [306]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2501 entries, 0 to 2500
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   產業           2501 non-null   object
 1   公司名稱         2501 non-null   object
 2   description  2501 non-null   object
 3   縣市           2501 non-null   object
 4   職稱           2501 non-null   object
 5   工作編號         2501 non-null   int64
 6   經度           2501 non-null   float64
 7   緯度           2501 non-null   float64
 8   major        2501 non-null   object
 9   學歷要求         2501 non-null   object
 10  是否遠距         2501 non-null   int64
 11  薪資下限         2501 non-null   int64
 12  條件要求         2501 non-null   object
 13  員工人數         2501 non-null   object
dtypes: float64(2), int64(3), object(9)
memory usage: 273.7+ KB

In [307]:
df.head()

,產業,公司名稱,description,縣市,職稱,工作編號,經度,緯度,major,學歷要求,是否遠距,薪資下限,條件要求,員工人數
0,電腦軟體服務業,不晚科技有限公司,1.熟練數據分析工具，能進行數據清理、分析和建模，分析市場營銷活動的效果，提供報告和改進建議...,台北市,數據分析,14325959,25.076077,121.575436,[],"[3, 4]",0,0,"{'acceptRole': {'role': [], 'disRole': {'needH...",20人
1,光電產業,鉅瀚綠能股份有限公司,1.進行調查數據的彙整，分析調查數據與繪製統計圖表，並撰寫分析建議報告。\n2.依據分析需求...,台中市,數據分析專員,14427852,24.161955,120.651687,"['統計學相關', '資訊工程相關']","[4, 5, 6]",0,39000,"{'acceptRole': {'role': [{'code': 2, 'descript...",40人
2,人力仲介代徵,藝珂人事顧問股份有限公司,工作內容：執行全球貿易大數據平台基金業務工作\n1.\t協助數據專案執行、廠商管理、專案委外...,台北市,【外貿協會】數位科技中心-數據分析師｜全球貿易大數據平台,14689540,25.033076,121.564508,[],[4],0,0,"{'acceptRole': {'role': [], 'disRole': {'needH...",暫不提供
3,雜誌／期刊出版業,今周刊_今周文化事業股份有限公司,1.【必備】Google Analytics技能。 \n2.【必備】熟稔Excel(函數、樞...,台北市,數據分析師【今周刊─數位內容部】,14090732,25.051911,121.526154,[],"[4, 5]",0,0,"{'acceptRole': {'role': [{'code': 64, 'descrip...",217人
4,家用電器製造業,金筆企業股份有限公司,1. 工廠生產數據收集、整理與分析，協助相關人員了解生產狀況\n2. 建立分析指標，追蹤並記...,新北市,數據分析工程師,14720195,25.068090,121.455088,"['數理統計相關', '其他數學及電算機科學相關', '工業工程相關']",[4],0,38000,"{'acceptRole': {'role': [], 'disRole': {'needH...",108人

# 薪資欄位處理
<p>薪資欄位: </p>
<p>1.「薪資下限」、「薪資上限」兩欄</p>
<p>2.【月薪】【時薪】【年薪】混雜</p>
<p>3.需多為0的資料</p>

In [308]:
df['薪資是否為面議']= np.where(df['薪資下限']==0,1,0) #增加'薪資是否為面議'欄位
df['薪資下限']=df['薪資下限'].replace(0,40000)    #將面議的改成法規規定最低40000
df=df[df['薪資下限']>=1000]     #將時薪(非正職、學生實習)的資料去除

#自動判斷月薪超過300000為年薪，並除以12，轉為月薪
df['薪資下限'] = df['薪資下限'].astype(float)   #原本欄位是(int)類型，除12後會變float，會相衝，故先轉成float。
df.loc[df['薪資下限'] > 300000, '薪資下限']/= 12
df['薪資下限'] = df['薪資下限'].round(0).astype(int)

## 增加欄位「是否要求特定major」，用來探索性分析。(*非本次分析重點，可略過)

In [309]:
df['major']

0                                         []
1                        ['統計學相關', '資訊工程相關']
2                                         []
3                                         []
4       ['數理統計相關', '其他數學及電算機科學相關', '工業工程相關']
                        ...
2496                                      []
2497                                      []
2498    ['數理統計相關', '工業工程相關', '其他數學及電算機科學相關']
2499                                      []
2500    ['企業管理相關', '資訊管理相關', '其他數學及電算機科學相關']
Name: major, Length: 2432, dtype: object

In [310]:
import ast # 導入 ast 模組
df["是否要求特定major"] = df['major'].apply(lambda x: 1 if len(ast.literal_eval(x)) > 0 else 0) #增加一欄，[是否要求特定major]的欄位。

In [311]:
df['是否要求特定major'].tail(20)

2481    1
2482    0
2483    0
2484    0
2485    0
2486    1
2487    0
2488    0
2489    0
2490    0
2491    0
2492    0
2493    1
2494    0
2495    1
2496    0
2497    0
2498    1
2499    0
2500    1
Name: 是否要求特定major, dtype: int64

## 將 「是否遠距」欄位原本的編碼，還原為對應的字串(*非本次分析重點，可略過)

In [312]:
df['是否遠距'].value_counts()

是否遠距
0    2199
2     212
1      21
Name: count, dtype: int64

In [313]:
df['是否遠距'] = df['是否遠距'].astype(int)

In [314]:
remote_work={0:"無遠距",1:"完全遠距",2:"混和"}
df['是否遠距']=df['是否遠距'].map(remote_work)

In [315]:
df.head()

,產業,公司名稱,description,縣市,職稱,工作編號,經度,緯度,major,學歷要求,是否遠距,薪資下限,條件要求,員工人數,薪資是否為面議,是否要求特定major
0,電腦軟體服務業,不晚科技有限公司,1.熟練數據分析工具，能進行數據清理、分析和建模，分析市場營銷活動的效果，提供報告和改進建議...,台北市,數據分析,14325959,25.076077,121.575436,[],"[3, 4]",無遠距,40000,"{'acceptRole': {'role': [], 'disRole': {'needH...",20人,1,0
1,光電產業,鉅瀚綠能股份有限公司,1.進行調查數據的彙整，分析調查數據與繪製統計圖表，並撰寫分析建議報告。\n2.依據分析需求...,台中市,數據分析專員,14427852,24.161955,120.651687,"['統計學相關', '資訊工程相關']","[4, 5, 6]",無遠距,39000,"{'acceptRole': {'role': [{'code': 2, 'descript...",40人,0,1
2,人力仲介代徵,藝珂人事顧問股份有限公司,工作內容：執行全球貿易大數據平台基金業務工作\n1.\t協助數據專案執行、廠商管理、專案委外...,台北市,【外貿協會】數位科技中心-數據分析師｜全球貿易大數據平台,14689540,25.033076,121.564508,[],[4],無遠距,40000,"{'acceptRole': {'role': [], 'disRole': {'needH...",暫不提供,1,0
3,雜誌／期刊出版業,今周刊_今周文化事業股份有限公司,1.【必備】Google Analytics技能。 \n2.【必備】熟稔Excel(函數、樞...,台北市,數據分析師【今周刊─數位內容部】,14090732,25.051911,121.526154,[],"[4, 5]",無遠距,40000,"{'acceptRole': {'role': [{'code': 64, 'descrip...",217人,1,0
4,家用電器製造業,金筆企業股份有限公司,1. 工廠生產數據收集、整理與分析，協助相關人員了解生產狀況\n2. 建立分析指標，追蹤並記...,新北市,數據分析工程師,14720195,25.068090,121.455088,"['數理統計相關', '其他數學及電算機科學相關', '工業工程相關']",[4],無遠距,38000,"{'acceptRole': {'role': [], 'disRole': {'needH...",108人,0,1

# 去除「工作編號」重複的資料，設定「工作編號」為index

In [316]:
df[df["工作編號"].duplicated()]

,產業,公司名稱,description,縣市,職稱,工作編號,經度,緯度,major,學歷要求,是否遠距,薪資下限,條件要求,員工人數,薪資是否為面議,是否要求特定major
330,其它軟體及網路相關業,遊戲橘子數位科技股份有限公司,此為橘子集團旗下的行動支付服務品牌， 全面推廣電子支付的服務版圖。我們致力推廣電子支付應用範...,台北市,數據分析師,12828775,25.071724,121.576463,"['統計學相關', '數理統計相關']","[3, 4, 5]",無遠距,40000,"{'acceptRole': {'role': [{'code': 2, 'descript...",1000人,1,1
374,電腦軟體服務業,艾奈科技有限公司,\n\n▍About this role\n\n您將擔任 資料分析師 Data Analys...,台北市,資料分析師 Data Analyst,14665065,25.041560,121.563001,[],"[4, 5]",無遠距,83333,"{'acceptRole': {'role': [], 'disRole': {'needH...",120人,0,0
389,其他金融及輔助業,裕隆集團_新鑫股份有限公司,我們正積極招募優秀人才，需要熱血有想法的夥伴們一同推進新一代資訊系統轉型，本職缺將會進行數據...,台北市,【資訊人員】資訊數據工程師-依學經歷核敘,14723807,25.032993,121.548364,[],"[4, 5, 6]",無遠距,40000,"{'acceptRole': {'role': [], 'disRole': {'needH...",800人,1,0
426,電腦軟體服務業,旭捷資訊有限公司,工作內容\n◆ 數據處理 - 建立資料倉儲、資料湖，ETL 工具與流程\n◆ 數據串接 - ...,台北市,數據工程師,13898661,25.056504,121.533383,[],"[4, 5]",無遠距,40000,"{'acceptRole': {'role': [], 'disRole': {'needH...",40人,1,0
427,電腦軟體服務業,恆昌科技有限公司,工作內容：\n1.ETL流程設計和實施數據提取、轉換和加載流程，從體育數據源（賽事結果、玩家...,台中市,數據工程師,14506237,24.176976,120.642433,[],"[3, 4, 5]",混和,45000,"{'acceptRole': {'role': [], 'disRole': {'needH...",暫不提供,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,其他金融及輔助業,國?租賃股份有限公司,1.進行資料收集、標籤定義與數據清理。\n2.進行調查數據的彙整，分析調查數據與繪製統計圖表...,台北市,【數位行銷】數據分析師,14116487,25.042557,121.512109,[],"[4, 5, 6]",無遠距,40000,"{'acceptRole': {'role': [], 'disRole': {'needH...",100人,1,0
2497,人力仲介代徵,藝珂人事顧問股份有限公司,工作內容：執行全球貿易大數據平台基金業務工作\n1.\t協助數據專案執行、廠商管理、專案委外...,台北市,【外貿協會】數位科技中心-數據分析師｜全球貿易大數據平台-有金融產業或電信業分析經歷尤佳_O...,14759492,25.033076,121.564508,[],[4],無遠距,40000,"{'acceptRole': {'role': [], 'disRole': {'needH...",暫不提供,1,0
2498,半導體製造業,錼創顯示科技股份有限公司,1. 分析生產數據與大數據建模，協助建立品質監測與異常偵測模型，提供優化建議。\n2. 參與...,苗栗縣,數據分析工程師,14535114,24.711336,120.913172,"['數理統計相關', '工業工程相關', '其他數學及電算機科學相關']",[5],無遠距,40000,"{'acceptRole': {'role': [], 'disRole': {'needH...",500人,1,1
2499,大專校院教育事業,國立臺北科技大學,作，成果應用於企業與政府智慧城市專案。加入我們，您將成為城市科學的先鋒，與世界領先的團隊共創...,台北市,MITxTaipei Tech 都市數據分析師,13817654,25.041802,121.534887,[],"[4, 5, 6]",無遠距,40000,"{'acceptRole': {'role': [{'code': 2, 'descript...",暫不提供,1,0
2500,診所,馬光醫療網_馬光中醫診所,工作內容\n*分析內部營運相關數據，製作營運儀表板，提供決策依據\n*針對經營議題（如選址、...,高雄市,策略數據分析師｜產業洞察×跨部門數據整合,14685273,22.624723,120.361266,"['企業管理相關', '資訊管理相關', '其他數學及電算機科學相關']","[3, 4, 5]",無遠距,40000,"{'acceptRole': {'role': [{'code': 4, 'descript...",700人,1,1

In [317]:
df.drop_duplicates(subset="工作編號",keep="first",inplace=True)  #保留第一個

In [318]:
df.set_index("工作編號")

,產業,公司名稱,description,縣市,職稱,經度,緯度,major,學歷要求,是否遠距,薪資下限,條件要求,員工人數,薪資是否為面議,是否要求特定major
工作編號,,,,,,,,,,,,,,,
14325959,電腦軟體服務業,不晚科技有限公司,1.熟練數據分析工具，能進行數據清理、分析和建模，分析市場營銷活動的效果，提供報告和改進建議...,台北市,數據分析,25.076077,121.575436,[],"[3, 4]",無遠距,40000,"{'acceptRole': {'role': [], 'disRole': {'needH...",20人,1,0
14427852,光電產業,鉅瀚綠能股份有限公司,1.進行調查數據的彙整，分析調查數據與繪製統計圖表，並撰寫分析建議報告。\n2.依據分析需求...,台中市,數據分析專員,24.161955,120.651687,"['統計學相關', '資訊工程相關']","[4, 5, 6]",無遠距,39000,"{'acceptRole': {'role': [{'code': 2, 'descript...",40人,0,1
14689540,人力仲介代徵,藝珂人事顧問股份有限公司,工作內容：執行全球貿易大數據平台基金業務工作\n1.\t協助數據專案執行、廠商管理、專案委外...,台北市,【外貿協會】數位科技中心-數據分析師｜全球貿易大數據平台,25.033076,121.564508,[],[4],無遠距,40000,"{'acceptRole': {'role': [], 'disRole': {'needH...",暫不提供,1,0
14090732,雜誌／期刊出版業,今周刊_今周文化事業股份有限公司,1.【必備】Google Analytics技能。 \n2.【必備】熟稔Excel(函數、樞...,台北市,數據分析師【今周刊─數位內容部】,25.051911,121.526154,[],"[4, 5]",無遠距,40000,"{'acceptRole': {'role': [{'code': 64, 'descrip...",217人,1,0
14720195,家用電器製造業,金筆企業股份有限公司,1. 工廠生產數據收集、整理與分析，協助相關人員了解生產狀況\n2. 建立分析指標，追蹤並記...,新北市,數據分析工程師,25.068090,121.455088,"['數理統計相關', '其他數學及電算機科學相關', '工業工程相關']",[4],無遠距,38000,"{'acceptRole': {'role': [], 'disRole': {'needH...",108人,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14741596,電腦軟體服務業,大門科技顧問有限公司,學、資訊工程、商業分析、數學等相關科系尤佳），具備 5 年以上網路產業相關數據分析／挖掘／B...,高雄市,【南】Data Analyst – Advertising｜數據分析師－廣告成效（完全遠端）,22.626881,120.326254,[],"[4, 5, 6]",完全遠距,40000,"{'acceptRole': {'role': [{'code': 2, 'descript...",50人,1,0
14552797,銀行業,彰化商業銀行股份有限公司,※必要資格條件 \n1.學歷：國內、外大學(含)以上畢業，且已取得畢業證書(請提供相關修課紀...,台北市,數據工程師,25.079202,121.542709,[],"[4, 5, 6]",無遠距,48600,"{'acceptRole': {'role': [{'code': 64, 'descrip...",6400人,0,0
14531062,百貨相關業,富邦媒體科技股份有限公司(富邦momo),化工具，如 Tableau、Power BI、Looker。\n3. 雲端與大數據技術：\n...,台北市,D4000 資訊課級主管(資料分析與架構研發),25.079797,121.570957,[],"[4, 5, 6]",無遠距,40000,"{'acceptRole': {'role': [], 'disRole': {'needH...",3000人,1,0
14424533,廣告行銷公關業,華權數位整合行銷有限公司,主要工作述敘：\n1. 數據分析與精算：\n■分析遊戲玩家行為數據、直播主表現數據，協助優化...,台中市,數據分析師,24.116516,120.615540,"['統計學相關', '數理統計相關', '應用數學相關']","[4, 5, 6]",無遠距,40000,"{'acceptRole': {'role': [{'code': 2, 'descript...",暫不提供,0,1
14620764,其他相關製造業,CONTIN 康定_奇來生技有限公司,團媽 合作效益追蹤機制，量化其曝光、導流與銷售成效，並提出合作優化建議。\n\n3.利用 G...,高雄市,數位行銷數據分析師,22.641587,120.385938,[],"[3, 4, 5, 6]",無遠距,40000,"{'acceptRole': {'role': [], 'disRole': {'needH...",暫不提供,0,0

# 縮減「產業」欄位成「八大產業」
<p>因為104產業類型太多，且許多產業是非常相同的，不利於分析，故將類似的行業整合在一起</p>

In [319]:
#未縮減前，有81種產業別
df['產業'].nunique()

103

In [320]:
#請參考同資料夾內 cleaning_industry.py 內容，其中有整合mapping對照表。
#這邊直接匯入預寫好的函數進行處理
from cleaning_industry import clean_industry_column
df=clean_industry_column(df)
df.drop(columns=["產業"],inplace=True)

In [321]:
df["八大產業"].value_counts()

八大產業
資訊科技業       293
金融與保險業      155
服務與專業顧問業    145
製造業         116
批發與零售業       55
醫療與健康照護      33
其他           28
觀光與餐飲業       12
運輸與物流業        8
Name: count, dtype: int64

In [322]:
df.head()

,公司名稱,description,縣市,職稱,工作編號,經度,緯度,major,學歷要求,是否遠距,薪資下限,條件要求,員工人數,薪資是否為面議,是否要求特定major,八大產業
0,不晚科技有限公司,1.熟練數據分析工具，能進行數據清理、分析和建模，分析市場營銷活動的效果，提供報告和改進建議...,台北市,數據分析,14325959,25.076077,121.575436,[],"[3, 4]",無遠距,40000,"{'acceptRole': {'role': [], 'disRole': {'needH...",20人,1,0,資訊科技業
1,鉅瀚綠能股份有限公司,1.進行調查數據的彙整，分析調查數據與繪製統計圖表，並撰寫分析建議報告。\n2.依據分析需求...,台中市,數據分析專員,14427852,24.161955,120.651687,"['統計學相關', '資訊工程相關']","[4, 5, 6]",無遠距,39000,"{'acceptRole': {'role': [{'code': 2, 'descript...",40人,0,1,製造業
2,藝珂人事顧問股份有限公司,工作內容：執行全球貿易大數據平台基金業務工作\n1.\t協助數據專案執行、廠商管理、專案委外...,台北市,【外貿協會】數位科技中心-數據分析師｜全球貿易大數據平台,14689540,25.033076,121.564508,[],[4],無遠距,40000,"{'acceptRole': {'role': [], 'disRole': {'needH...",暫不提供,1,0,服務與專業顧問業
3,今周刊_今周文化事業股份有限公司,1.【必備】Google Analytics技能。 \n2.【必備】熟稔Excel(函數、樞...,台北市,數據分析師【今周刊─數位內容部】,14090732,25.051911,121.526154,[],"[4, 5]",無遠距,40000,"{'acceptRole': {'role': [{'code': 64, 'descrip...",217人,1,0,服務與專業顧問業
4,金筆企業股份有限公司,1. 工廠生產數據收集、整理與分析，協助相關人員了解生產狀況\n2. 建立分析指標，追蹤並記...,新北市,數據分析工程師,14720195,25.068090,121.455088,"['數理統計相關', '其他數學及電算機科學相關', '工業工程相關']",[4],無遠距,38000,"{'acceptRole': {'role': [], 'disRole': {'needH...",108人,0,1,製造業

# 處理「學歷要求」欄位

In [323]:
#查看該欄位有哪些不同的值，以及有多少數量
df["學歷要求"].value_counts()

學歷要求
[4, 5, 6]             310
[4, 5]                208
[1, 2, 3, 4, 5, 6]     70
[3, 4, 5, 6]           64
[5, 6]                 57
[3, 4, 5]              47
[5]                    30
[4]                    29
[3, 4]                 10
[2, 3, 4, 5, 6]         9
[3]                     4
[2, 3, 4, 5]            3
[6]                     3
[2, 3, 4]               1
Name: count, dtype: int64

### 產生對照字典，並依據最小的值去對照(學歷最低要求水準)(*非本次分析重點，可略過)

In [324]:
edu_map = {
            1: '不拘',
            2: '高中',
            3: '專科',
            4: '大學',
            5: '碩士',
            6: '博士',
        }
df['學歷要求']=df['學歷要求'].apply(lambda x:edu_map.get(min(ast.literal_eval(x))))

### 透過公司人數，增加「公司規模」欄位，判斷是【大型公司】【中型公司】【小型公司】(*非本次分析重點，可略過)

In [325]:
df['員工人數'] = df['員工人數'].apply(lambda x: int(x.replace('人', '')) if isinstance(x, str) and x.endswith('人') else pd.NA) # 去'人'轉數字，並將'暫不提供'改為NA

In [326]:
#增加[公司規模]欄位，依員工人數劃分
def classify_company_size(num):       
    if pd.isnull(num):
        return '未知'
    elif num<50:
        return '小型'
    elif num < 200:
        return '中型'
    else:
        return '大型'
df['公司規模']=df['員工人數'].apply(classify_company_size)

# 處理「條件要求」欄位
<p>該欄資料是一串dictionary，可以拆成許多欄位。</p>
<p>本次處理重點為，拆出「專長工具」與「工作經驗」這兩個欄位。</p>
<p>「專長工具」可以做為後續【核心技能要求】的分析。</p>

In [327]:
import pandas as pd
import ast # 確保 ast 模組已被導入
import re  # 導入正則表達式模組，用於更精確的關鍵字匹配

# --- 請您自行擴充和完善這個工具關鍵字列表 ---
# 這個列表越完整，從文本中提取的效果越好。
# 建議將常用、特定領域的工具名稱都加進去。
TOOL_KEYWORDS = [
    'Python', 'R', 'SQL', 'Excel', 'Tableau', 'PowerBI', 'Hadoop', 'Spark', 'Kafka',
    'TensorFlow', 'Pytorch', 'Keras', 'Scikit-learn', 'NumPy', 'Pandas', 'Matplotlib', 'Seaborn',
    'AWS', 'Azure', 'GCP', 'Docker', 'Kubernetes', 'Git', 'Linux', 'Java', 'C++', 'Scala', 'Go',
    'SAS', 'SPSS', 'ETL', 'API', 'SSIS', 'SSRS', 'SSAS', 'Power BI', 'QlikView', 'D3.js', 'NoSQL',
    'MongoDB', 'PostgreSQL', 'MySQL', 'Redshift', 'BigQuery', 'Snowflake', 'Airflow', 'Luigi',
    'Jupyter', 'VS Code', 'GitLab', 'GitHub', 'CI/CD', 'Machine Learning', 'Deep Learning',
    '統計', '數據分析', '數據挖掘', '機器學習', '深度學習', '資料庫', '雲端', '自動化',
    'BI', 'Dashboard', '報表', '可視化', '自然語言處理', 'NLP', '計算機視覺', 'CV',
    'A/B Testing', '模型部署', 'MLOps', 'Data Bricks', 'Databricks', 'Dataproc',
    'Looker Studio', 'Snowflake', 'GCP' # <--- 已將這些新的工具關鍵字加入
]
# 將關鍵字按長度降序排列，以避免短詞匹配先於長詞（例如先匹配 'SQL' 再匹配 'MySQL'）
TOOL_KEYWORDS = sorted(TOOL_KEYWORDS, key=len, reverse=True)


def parse_string(x):
    """
    將字串轉換為 Python 的資料結構（如字典、列表、數字等）。
    """
    if isinstance(x, str):
        try:
            return ast.literal_eval(x)
        except Exception as e:
            # 您可以選擇在這裡加入錯誤處理或日誌記錄
            # print(f"Error parsing: {x} - {e}")
            return {} # 解析失敗時返回空字典，方便後續處理
    return x

def extract_all_tools_from_row(row):
    """
    從 '條件要求' 字典內的 'specialty' 和 '其他條件'，以及獨立的 'description' 欄位中，
    提取所有相關的工具名稱。此函數需要對 DataFrame 進行 row-wise 應用 (df.apply(..., axis=1))。
    """
    extracted_tools = set() # 使用集合來自動處理重複項

    # 輔助函數：用於在文本中更精確地查找關鍵字（使用詞邊界）
    def find_keywords_in_text(text, keywords_list):
        if not isinstance(text, str):
            return []
        found = set()
        text_lower = text.lower()
        for keyword in keywords_list:
            # 使用正則表達式，並加上 \b 詞邊界，確保只匹配完整的詞
            # re.escape 用於處理關鍵字中可能存在的正則表達式特殊字元 (例如 C++, D3.js)
            if re.search(r'\b' + re.escape(keyword.lower()) + r'\b', text_lower):
                found.add(keyword)
        return list(found)

    # --- 1. 從 '條件要求' 字典的 'specialty' 提取 ---
    job_require_dict = row.get('條件要求') # 安全地獲取 '條件要求' 欄位的值
    if isinstance(job_require_dict, dict) and 'specialty' in job_require_dict:
        specialty_list = job_require_dict['specialty']
        if isinstance(specialty_list, list):
            for s in specialty_list:
                if isinstance(s, dict) and s.get('description'):
                    desc_from_specialty = s['description']
                    # 將 specialty 的 description 直接加入（如果它本身就是一個工具名）
                    if isinstance(desc_from_specialty, str):
                        extracted_tools.add(desc_from_specialty)
                    
                    # 同時檢查 specialty 的 description 是否包含預定義的工具關鍵字
                    found_in_desc = find_keywords_in_text(desc_from_specialty, TOOL_KEYWORDS)
                    extracted_tools.update(found_in_desc)

    # --- 2. 從 '條件要求' 字典的 '其他條件' 提取 ---
    if isinstance(job_require_dict, dict) and '其他條件' in job_require_dict:
        other_conditions_text = job_require_dict['其他條件']
        found_in_other = find_keywords_in_text(other_conditions_text, TOOL_KEYWORDS)
        extracted_tools.update(found_in_other)

    # --- 3. 從獨立的 'description' 欄位提取 ---
    description_text = row.get('description') # 從行中安全地獲取獨立的 'description' 欄位值
    found_in_main_desc = find_keywords_in_text(description_text, TOOL_KEYWORDS)
    extracted_tools.update(found_in_main_desc)
    
    # 將提取到的所有工具名稱合併為一個逗號分隔的字串，並去除重複項
    if extracted_tools:
        # 排除空字符串或None，並排序以保持輸出一致性
        final_tools = [tool for tool in extracted_tools if tool and pd.notna(tool)]
        return ", ".join(sorted(final_tools))
    else:
        return None

# --- 以下是應用程式碼 ---

# 假設 df DataFrame 已經被載入
# df = pd.read_csv('your_data.csv') # 如果還沒載入，請在這裡載入

# 1. 將 '條件要求' 字串轉換為 Python 的資料結構
df['條件要求'] = df['條件要求'].apply(parse_string)

# 2. 提取工作經驗 (保持與您原有程式碼一致)
df['工作經驗'] = df['條件要求'].apply(lambda x:x.get('workExp') if isinstance(x,dict) else None)

# 3. 提取所有工具名稱 (取代原本的 '專長工具' 提取邏輯)
# 注意：這裡使用 df.apply(..., axis=1) 因為 extract_all_tools_from_row 需要訪問整行數據
df['所有工具'] = df.apply(extract_all_tools_from_row, axis=1)

# 4. 刪除原始的 '條件要求' 欄位 (保持與您原有程式碼一致)
df.drop(columns='條件要求', inplace=True)

# --- 完成處理，您可以檢查新生成的欄位 ---
# print(df[['工作經驗', '所有工具']].head())

In [328]:
df.tail()

,公司名稱,description,縣市,職稱,工作編號,經度,緯度,major,學歷要求,是否遠距,薪資下限,員工人數,薪資是否為面議,是否要求特定major,八大產業,公司規模,工作經驗,所有工具
2482,大門科技顧問有限公司,學、資訊工程、商業分析、數學等相關科系尤佳），具備 5 年以上網路產業相關數據分析／挖掘／B...,高雄市,【南】Data Analyst – Advertising｜數據分析師－廣告成效（完全遠端）,14741596,22.626881,120.326254,[],大學,完全遠距,40000,50,1,0,資訊科技業,中型,5年以上,"BI, Excel, Python, SQL, Tableau"
2485,彰化商業銀行股份有限公司,※必要資格條件 \n1.學歷：國內、外大學(含)以上畢業，且已取得畢業證書(請提供相關修課紀...,台北市,數據工程師,14552797,25.079202,121.542709,[],大學,無遠距,48600,6400,0,0,金融與保險業,大型,3年以上,Tableau
2492,富邦媒體科技股份有限公司(富邦momo),化工具，如 Tableau、Power BI、Looker。\n3. 雲端與大數據技術：\n...,台北市,D4000 資訊課級主管(資料分析與架構研發),14531062,25.079797,121.570957,[],大學,無遠距,40000,3000,1,0,批發與零售業,大型,7年以上,"AWS, Azure, BI, Databricks, Power BI, Snowflak..."
2495,華權數位整合行銷有限公司,主要工作述敘：\n1. 數據分析與精算：\n■分析遊戲玩家行為數據、直播主表現數據，協助優化...,台中市,數據分析師,14424533,24.116516,120.615540,"['統計學相關', '數理統計相關', '應用數學相關']",大學,無遠距,40000,<NA>,0,1,服務與專業顧問業,未知,1年以上,None
2496,CONTIN 康定_奇來生技有限公司,團媽 合作效益追蹤機制，量化其曝光、導流與銷售成效，並提出合作優化建議。\n\n3.利用 G...,高雄市,數位行銷數據分析師,14620764,22.641587,120.385938,[],專科,無遠距,40000,<NA>,0,0,製造業,未知,2年以上,"Facebook, Google Analytics, Google Trend, Goog..."

### 將清理完成的資料，匯出成CSV

In [329]:
df.shape

(845, 18)

In [330]:
#暫時匯出
desktop_path = os.path.join(os.path.expanduser("~"), "Desktop", "104job_0804.csv")
df.to_csv(desktop_path, index=False, encoding='utf-8-sig')